name: my_manga_collection
description: Follow and track your manga collection easily with a simple Flutter
  application using Kitsu API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  collection: ^1.16.0
  connectivity_plus: ^2.3.2
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  dynamic_theme:
    git:
      url: https://github.com/TesteurManiak/dynamic_theme.git
      ref: 2.0.0
  easy_localization: ^3.0.1
  equatable: ^2.0.3
  file_picker: ^4.6.1
  flutter:
    sdk: flutter
  flutter_file_saver: ^0.5.1
  flutter_riverpod: ^1.0.4
  go_router: ^3.1.1
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  like_button: ^2.0.4
  rxdart: ^0.27.4

dev_dependencies:
  alchemist: ^0.3.3
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.2
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  mocktail: ^0.3.0
  remove_from_coverage: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic_launcher.png"

flutter_native_splash:
  image: assets/splash/icon.png
  color: "#448AFF"
  android_12:
    image: assets/splash/icon.png
    color: "#448AFF"
