name: my_manga_collection
description: Follow and track your manga collection easily with a simple Flutter
  application using Kitsu API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  collection: ^1.16.0
  connectivity_plus: ^2.3.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dynamic_theme:
    git:
      url: https://github.com/TesteurManiak/dynamic_theme.git
      ref: 2.0.0
  easy_localization: ^3.0.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  go_router: ^3.1.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  rxdart: ^0.27.4
  shared_preferences: ^2.0.15

dev_dependencies:
  alchemist: ^0.3.3
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic_launcher.png"
  image_path_ios: "assets/icons/ic_launcher_ios.png"

flutter_native_splash:
  color: "#F5F5F5"
  color_dark: "#222727"
  android_12:
    color: "#F5F5F5"
    color_dark: "#222727"
